# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicView',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='msgboard.Topic')),
            ],
            bases=('msgboard.topic',),
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='TopicId',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='boardId',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='userId',
            new_name='user',
        ),
    ]
